version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-stomp
    ports:
      - "5672:5672"   # AMQP port
      - "15672:15672" # Management UI
      - "61613:61613" # STOMP port
    volumes:
      - ./rabbitmq-enabled-plugins:/etc/rabbitmq/enabled_plugins
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest